using Microsoft.SqlServer.Dac.Model;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using System.Collections.Generic;
using System.Linq;
using ssdt = Microsoft.SqlServer.Dac.Model;


namespace SSDTScaffolderLib.Models
{
    public class Table
    {
        public Table()
        {
            
        }

        public string Schema { get; internal set; }
        public string Name { get; internal set; }
        public bool IsAutoGeneratedHistoryTable { get; internal set; }
        public bool MemoryOptimized { get; internal set; }

        public List<Column> Columns { get; internal set; }
    }
}